openapi: 3.0.1
info:
  title: Order API
  version: "2.0"
servers:
  - url: "http://localhost:3000"
tags:
  - name: Product
    description: Product related APIs.
  - name: Order
    description: Order related APIs.
paths:
  "/products/{id}":
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Product identifier.
        examples:
          GET_DETAILS:
            value: 10
          UPDATE_DETAILS:
            value: 10
          DELETE_PRODUCT:
            value: 20
          INVALID_ID:
            value: 344
    get:
      summary: Fetch product details
      tags:
        - Product
      description: Fetch product details.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yml#/components/schemas/Product"
              examples:
                GET_DETAILS:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
                    id: 10
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Not found"
      operationId: get-product-id
    post:
      summary: Update product details
      operationId: post-products-id
      tags:
        - Product
      description: Update product details.
      responses:
        "200":
          description: Update successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_DETAILS:
                  value: "success"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "415":
          $ref: "./common_responses.yml#/components/responses/UnsupportedMediaType"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./common.yml#/components/schemas/Product"
            examples:
              UPDATE_DETAILS:
                value:
                  name: "XYZ Fone"
                  type: "gadget"
                  inventory: 10
                  id: 10
    delete:
      summary: Delete a product
      operationId: delete-products-id
      tags:
        - Product
      description: Delete a product.
      responses:
        "200":
          description: Deletion successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
  /products:
    get:
      summary: GET Products based on type
      operationId: get-products
      tags:
        - Product
      description: Get products based on type.
      parameters:
        - name: type
          in: query
          description: Filter products by type.
          schema:
            type: string
            enum:
              - gadget
              - book
              - food
              - other
      responses:
        "200":
          description: List of products in the response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "common.yml#/components/schemas/Product"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
    post:
      summary: POST /products
      operationId: post-products
      tags:
        - Product
      description: Create a product.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "common.yml#/components/schemas/ProductDetails"
      responses:
        "200":
          description: POST /products
          content:
            application/json:
              schema:
                $ref: "common.yml#/components/schemas/ProductId"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "415":
          $ref: "./common_responses.yml#/components/responses/UnsupportedMediaType"
  /orders:
    post:
      summary: POST /orders
      operationId: post-orders
      tags:
        - Order
      description: Create an order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "common.yml#/components/schemas/OrderDetails"
            examples:
              CREATE_ORDER:
                value:
                  productid: 10
                  count: 2
                  status: pending
      responses:
        "200":
          description: POST /orders
          content:
            application/json:
              schema:
                $ref: "common.yml#/components/schemas/OrderId"
              examples:
                CREATE_ORDER:
                  value:
                    id: 10
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "415":
          $ref: "./common_responses.yml#/components/responses/UnsupportedMediaType"
    get:
      summary: Search for orders
      operationId: get-orders
      tags:
        - Order
      description: Search for orders.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yml#/components/schemas/Order"
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: "pending"
                      id: 10
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
      parameters:
        - schema:
            type: integer
          in: query
          name: productid
          description: Filter orders by product identifier.
          examples:
            200_OK:
              value: 10
        - schema:
            type: string
          in: query
          name: status
          description: Filter orders by order status.
          examples:
            200_OK:
              value: fulfilled
  "/orders/{id}":
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Order identifier.
        examples:
          DETAILS:
            value: 10
          INVALID_ID:
            value: 433
    get:
      summary: Fetch order details
      tags:
        - Order
      description: Fetch order details.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yml#/components/schemas/Order"
              examples:
                DETAILS:
                  value:
                    productid: 10
                    count: 2
                    status: "pending"
                    id: 10
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Product with id 344 was not found"
      operationId: get-orders-id
    post:
      summary: Update order details
      operationId: post-orders-id
      tags:
        - Order
      description: Update order details.
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
        "415":
          $ref: "./common_responses.yml#/components/responses/UnsupportedMediaType"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./common.yml#/components/schemas/Order"
            examples:
              UPDATE_ORDER:
                value:
                  productid: 10
                  id: 10
                  count: 1
                  status: pending
    delete:
      summary: Cancel an order
      operationId: delete-orders-id
      tags:
        - Order
      description: Cancel an order.
      responses:
        "200":
          description: Cancel successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yml#/components/responses/BadRequest"
components:
  schemas:
    ErrorResponseBody:
      properties:
        id:
          type: number
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string

  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: keycloak based oauth security example
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8083/realms/specmatic/protocol/openid-connect/auth
          tokenUrl: http://localhost:8083/realms/specmatic/protocol/openid-connect/token
          scopes:
            email: email

security:
  - oAuth2AuthCode: []
